/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  NftMarketplace,
  NftMarketplaceInterface,
} from "../../../contracts/Dao.sol/NftMarketplace";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "available",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "purchase",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class NftMarketplace__factory {
  static readonly abi = _abi;
  static createInterface(): NftMarketplaceInterface {
    return new Interface(_abi) as NftMarketplaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NftMarketplace {
    return new Contract(address, _abi, runner) as unknown as NftMarketplace;
  }
}
