/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  NftToken,
  NftTokenInterface,
} from "../../../contracts/Dao.sol/NftToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NftToken__factory {
  static readonly abi = _abi;
  static createInterface(): NftTokenInterface {
    return new Interface(_abi) as NftTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): NftToken {
    return new Contract(address, _abi, runner) as unknown as NftToken;
  }
}
